#!/usr/bin/env bash

set -e

pushd terraform


if ! aws s3 ls s3://wireguard-vpn > /dev/null 2>&1; then
    echo "Creating S3 bucket for terraform"
    aws s3 mb s3://wireguard-vpn
    aws s3api put-object --bucket wireguard-vpn --key terraform
else
    echo "S3 bucket already exists, skipping creation"; 
fi


echo "Running terrafor apply"
terraform init -input=false -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}" -backend-config="region=${AWS_REGION}" -reconfigure 
terraform fmt
terraform apply -input=false -auto-approve > /dev/null

echo "Infrastructure is ready"

popd