# This is a basic workflow to help you get started with Actions

name: Create Wireguard Platform on AWS

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Creation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setup the linux environment

        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt update
          sudo apt-get install --reinstall resolvconf
          sudo apt install -y ansible terraform wireguard

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          echo "Running init -----------"
          ./scripts/init
          echo "Running provision -----------"
          ./scripts/provision
          echo "Running configure -----------"
          ./scripts/configure
          echo "Running sending email"
          ./scripts/send-email
